name: Run Flow
description: 'Execute a named Cumulus flow'
inputs:
  org-name:
    description: 'Name of the scratch org or persistent org config to use'
    required: true
  flow-name:
    description: 'Name of the Cumulus flow to execute'
    required: true
  flow-options:
    description: 'Options for the Cumulus flow to include (format: key="value")'
    required: false
  debug:
    description: 'Display debug logs during Flow Execution'
    required: false
    default: false
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Run Flow
      env:
        CUMULUSCI_SERVICE_github: '{"username": "${{ github.actor }}", "token": "${{ github.token }}", "email": "cci@github.actions" }'
      shell: bash
      run: |
        declare -a FLOW_OPTIONS=()
        if [[ -n "${{ inputs.flow-options }}" ]]; then
          # Parse the input string carefully
          INPUT="${{ inputs.flow-options }}"
          KEY="${INPUT%%=*}"
          VALUE="${INPUT#*=}"
          
          # Handle the quoted value properly
          if [[ "$VALUE" == \"*\" ]]; then
            VALUE="${VALUE:1:-1}"  # Remove outer quotes
          fi
          
          # Only add options if we have both key and value
          if [[ -n "$KEY" ]] && [[ -n "$VALUE" ]]; then
            FLOW_OPTIONS=(-o "$KEY" "$VALUE")
          fi
        fi
        
        # Debug output
        echo "Input string: ${{ inputs.flow-options }}"
        echo "Parsed key: $KEY"
        echo "Parsed value: $VALUE"
        echo "Flow options: ${FLOW_OPTIONS[@]}"
        
        # Run the flow with proper array expansion
        if ${{ inputs.debug }}; then
          cci flow run "${{ inputs.flow-name }}" --org "${{ inputs.org-name }}" "${FLOW_OPTIONS[@]}" --debug | tee cumulusci-flow.log
        else
          cci flow run "${{ inputs.flow-name }}" --org "${{ inputs.org-name }}" "${FLOW_OPTIONS[@]}" | tee cumulusci-flow.log
        fi
