name: Run Flow
description: 'Execute a named Cumulus flow'
inputs:
  org-name:
    description: 'Name of the scratch org or persistent org config to use'
    required: true
  flow-name:
    description: 'Name of the Cumulus flow to execute'
    required: true
  debug:
    description: 'Display debug logs during Flow Execution'
    required: false
    default: 'false'
runs:
    using: "composite"
    steps:
      - name: Run Flow
        env:
          CUMULUSCI_SERVICE_github: '{"username": "${{ github.actor }}", "token": "${{ github.token }}", "email": "cci@github.actions" }'
        run: |
          if [ "${{ inputs.debug }}" = "true" ]; then
            cci flow run ${{ inputs.flow-name }} --org ${{ inputs.org-name }} --debug | tee cumulusci-flow.log
          else
            cci flow run ${{ inputs.flow-name }} --org ${{ inputs.org-name }} | tee cumulusci-flow.log
          fi
        shell: bash
